/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author admin
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setVisible(true);
        setResizable(true);
        setLocationRelativeTo(null);
        
        ImageIcon logoIcon = new ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Panel\\src\\picture\\Sti.png");
        ImageIcon upIcon = new ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Panel\\src\\picture\\up.png");
        ImageIcon studentIcon = new ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Panel\\src\\picture\\name.png");
        ImageIcon userIcon = new ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Panel\\src\\picture\\User.png");
        
        juser.setIcon(userIcon);
        jID.setIcon(studentIcon);
        jLabel_up.setIcon(upIcon);
        jLabel_logo.setIcon(logoIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_logo = new javax.swing.JLabel();
        jID = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        juser = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        bexit = new javax.swing.JToggleButton();
        jLabelRegister = new javax.swing.JLabel();
        blogin = new javax.swing.JToggleButton();
        jPanel_message = new javax.swing.JPanel();
        jLabel_up = new javax.swing.JLabel();
        jLabel_message_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(56, 56, 56));

        jPanel2.setBackground(new java.awt.Color(255, 215, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(2, 80, 146));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 238, 148));

        jLabel_logo.setOpaque(true);
        jLabel_logo.setPreferredSize(new java.awt.Dimension(125, 125));
        jPanel4.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 6, 156, 140));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        jID.setBackground(new java.awt.Color(255, 215, 0));
        jID.setOpaque(true);
        jID.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 30));
        jID.getAccessibleContext().setAccessibleName("25");
        jID.getAccessibleContext().setAccessibleDescription("25");

        ID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 370, 30));

        juser.setBackground(new java.awt.Color(255, 215, 0));
        juser.setOpaque(true);
        juser.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 30, 30));

        username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 370, 30));

        bexit.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        bexit.setText("EXIT");
        bexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jPanel2.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 180, -1));

        jLabelRegister.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegister.setText("Click here to create a new account");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 350, -1));

        blogin.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        blogin.setText("LOGIN");
        blogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        jPanel2.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 180, -1));

        jPanel_message.setBackground(new java.awt.Color(240, 52, 52));
        jPanel_message.setPreferredSize(new java.awt.Dimension(90, 90));

        jLabel_up.setBackground(new java.awt.Color(102, 255, 102));
        jLabel_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_upMouseClicked(evt);
            }
        });

        jLabel_message_text.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_message_text.setText("Message");

        javax.swing.GroupLayout jPanel_messageLayout = new javax.swing.GroupLayout(jPanel_message);
        jPanel_message.setLayout(jPanel_messageLayout);
        jPanel_messageLayout.setHorizontalGroup(
            jPanel_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_messageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_up, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_message_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_messageLayout.setVerticalGroup(
            jPanel_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_up, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_message_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 410, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        // TODO add your handling code here:
        new HomePage();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed
                     
    // Timer to hide the message panel
    Timer timerUp = new Timer(10, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            if(jPanel_message.getHeight() != 0)
                jPanel_message.setBounds(jPanel_message.getX(), jPanel_message.getY(), jPanel_message.getWidth(), jPanel_message.getHeight() - 5);
            else
                timerUp.stop();
        }
    });
    
    // Timer to show the message panel
    Timer timerDown = new Timer(10, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
             if(jPanel_message.getHeight() != 60)
                jPanel_message.setBounds(jPanel_message.getX(), jPanel_message.getY(), jPanel_message.getWidth(), jPanel_message.getHeight() + 5);
            else
                timerDown.stop();
        }
    });
    private void jLabel_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_upMouseClicked
        // Hide the jPanel message
        timerUp.start();
    }//GEN-LAST:event_jLabel_upMouseClicked

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:
         if(username.getText().trim().matches(""))
            jLabel_message_text.setText("Please fill out username!");
        
        else if(ID.getText().matches(""))
            jLabel_message_text.setText("Please fill out password!");
        
        else if(username.getText().matches("[Aa]dmin") && ID.getText().matches("admin@123")){
            JOptionPane.showMessageDialog(null, "Login successful :))");
            new Confirmation();
            dispose();
        }
        else{
            jLabel_message_text.setText("Wrong username or password!!");
            username.setText("");
            ID.setText("");
        }
        // Show the JPanel message
        timerDown.start();
    }//GEN-LAST:event_bloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JToggleButton bexit;
    private javax.swing.JToggleButton blogin;
    private javax.swing.JLabel jID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_message_text;
    private javax.swing.JLabel jLabel_up;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_message;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel juser;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
