/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author admin
 */
public final class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        
        setTitle("Register");
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(true);
        
        addPlaceHolder(jUsername);
        addPlaceHolder(jStudID);
        
        
    }
    
    //method for txt placeholder style and remove placeholder
    public void  addPlaceHolder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.GRAY);
    }
    
    public void removePlaceHolder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        roundedPanel1 = new test.RoundedPanel();
        jUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roundedPanel2 = new test.RoundedPanel();
        jStudID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roundedPanel3 = new test.RoundedPanel();
        jType = new javax.swing.JComboBox<>();
        roundedPanel4 = new test.RoundedPanel();
        jYear = new javax.swing.JComboBox<>();
        roundedPanel5 = new test.RoundedPanel();
        jCourse = new javax.swing.JComboBox<>();
        roundedPanel6 = new test.RoundedPanel();
        jSection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 242, 0));

        jPanel2.setBackground(new java.awt.Color(255, 242, 0));

        jPanel3.setBackground(new java.awt.Color(255, 242, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Sti.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 242, 0));

        jPanel5.setBackground(new java.awt.Color(255, 242, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 86, 225));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        roundedPanel1.setBackground(new java.awt.Color(59, 103, 236));

        jUsername.setBackground(new java.awt.Color(59, 103, 236));
        jUsername.setText("Username");
        jUsername.setToolTipText("Username");
        jUsername.setBorder(null);
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFocusLost(evt);
            }
        });
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/User.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUsername)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        roundedPanel2.setBackground(new java.awt.Color(59, 103, 236));

        jStudID.setBackground(new java.awt.Color(59, 103, 236));
        jStudID.setText("Student ID");
        jStudID.setToolTipText("Student ID");
        jStudID.setBorder(null);
        jStudID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jStudIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jStudIDFocusLost(evt);
            }
        });
        jStudID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStudIDActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/name.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStudID)
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStudID)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        roundedPanel3.setBackground(new java.awt.Color(59, 103, 236));

        jType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type of Students", "Regular", "Irregular" }));
        jType.setToolTipText("Regular or Irregular Student");
        jType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jType, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jType, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel4.setBackground(new java.awt.Color(59, 103, 236));

        jYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School Year", "1st", "2nd", "3rd", "4th" }));
        jYear.setToolTipText("Student Year");
        jYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jYear, 0, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jYear, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel5.setBackground(new java.awt.Color(59, 103, 236));

        jCourse.setMaximumRowCount(9);
        jCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course", "BSAIS", "BSCS", "BSCpE", "BSHM", "BSIT", "BMMA", "BSPsych", "BSTM" }));
        jCourse.setToolTipText("Course");
        jCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel6.setBackground(new java.awt.Color(59, 103, 236));

        jSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Section" }));

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSection, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(roundedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roundedPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roundedPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roundedPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jStudIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStudIDActionPerformed

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusGained
        // TODO add your handling code here:
        if (jUsername.getText().equals("Username")){
            jUsername.setText(null);
            jUsername.requestFocus();
            //remove placeholder style
            removePlaceHolder(jUsername);
        }
    }//GEN-LAST:event_jUsernameFocusGained

    private void jStudIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStudIDFocusGained
        // TODO add your handling code here:
        if (jStudID.getText().equals("Student ID")){
            jStudID.setText(null);
            jStudID.requestFocus();
            //remove placeholder style
            removePlaceHolder(jStudID);
        }
    }//GEN-LAST:event_jStudIDFocusGained

    private void jUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusLost
        // TODO add your handling code here:
        if (jUsername.getText().length()==0){
            //add the place holder style
            addPlaceHolder(jUsername);
            jUsername.setText("Username");
        }
    }//GEN-LAST:event_jUsernameFocusLost

    private void jStudIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStudIDFocusLost
        // TODO add your handling code here:
        if (jStudID.getText().length()==0){
            //add the place holder style
            addPlaceHolder(jStudID);
            jStudID.setText("Student ID");
        }
    }//GEN-LAST:event_jStudIDFocusLost

    private void jCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCourseActionPerformed
        // TODO add your handling code here:

        if (jCourse.getSelectedItem().equals("Course")){
            jSection.removeAllItems();
            jSection.addItem("Section");
        }
        else if (jCourse.getSelectedItem().equals("BSAIS")){
            jSection.removeAllItems();
            jSection.addItem("AIS101");
            jSection.addItem("AIS102");//1st year 1st sem
            jSection.addItem("AIS201");
            jSection.addItem("AIS202");//2nd sem
            jSection.addItem("AIS301");
            jSection.addItem("AIS302");//2nd year 1st sem
            jSection.addItem("AIS401");
            jSection.addItem("AIS402");//2nd sem
            jSection.addItem("AIS501");
            jSection.addItem("AIS502");//3rd year 1st sem
            jSection.addItem("AIS601");
            jSection.addItem("AIS601");//2nd sem
            jSection.addItem("AIS701");
            jSection.addItem("AIS702");//4th year 1st sem
            jSection.addItem("AIS801");
            jSection.addItem("AIS802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BSCS")){
            jSection.removeAllItems();
            jSection.addItem("BS101");
            jSection.addItem("BS102");//1st year 1st sem
            jSection.addItem("BS201");
            jSection.addItem("BS202");//2nd sem
            jSection.addItem("BS301");
            jSection.addItem("BS302");//2nd year 1st sem
            jSection.addItem("BS401");
            jSection.addItem("BS402");//2nd sem
            jSection.addItem("BS501");
            jSection.addItem("BS502");//3rd year 1st sem
            jSection.addItem("BS601");
            jSection.addItem("BS602");//2nd sem
            jSection.addItem("BS701");
            jSection.addItem("BS702");//4th year 1st sem
            jSection.addItem("BS801");
            jSection.addItem("BS802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BSCpE")){
            jSection.removeAllItems();
            jSection.addItem("COE101");
            jSection.addItem("COE102");//1st year 1st sem
            jSection.addItem("COE201");
            jSection.addItem("COE202");//2nd sem
            jSection.addItem("COE301");
            jSection.addItem("COE302");//2nd year 1st sem
            jSection.addItem("COE401");
            jSection.addItem("COE402");//2nd sem
            jSection.addItem("COE501");
            jSection.addItem("COE502");//3rd year 1st sem
            jSection.addItem("COE601");
            jSection.addItem("COE602");//2nd sem
            jSection.addItem("COE701");
            jSection.addItem("COE702");//4th year 1st sem
            jSection.addItem("COE801");
            jSection.addItem("COE802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BSHM")){
            jSection.removeAllItems();
            jSection.addItem("HM101");
            jSection.addItem("HM102");//1st year 1st sem
            jSection.addItem("HM201");
            jSection.addItem("HM202");//2nd sem
            jSection.addItem("HM301");
            jSection.addItem("HM302");//2nd year 1st sem
            jSection.addItem("HM401");
            jSection.addItem("HM402");//2nd sem
            jSection.addItem("HM501");
            jSection.addItem("HM502");//3rd year 1st sem
            jSection.addItem("HM601");
            jSection.addItem("HM602");//2nd sem
            jSection.addItem("HM701");
            jSection.addItem("HM702");//4th year 1st sem
            jSection.addItem("HM801");
            jSection.addItem("HM802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BSIT")){
            jSection.removeAllItems();
            jSection.addItem("BT101");
            jSection.addItem("BT102");//1st year 1st sem
            jSection.addItem("BT201");
            jSection.addItem("BT202");
            jSection.addItem("BT203");//2nd sem
            jSection.addItem("BT301");
            jSection.addItem("BT302");//2nd year 1st sem
            jSection.addItem("BT401");
            jSection.addItem("BT402");//2nd sem
            jSection.addItem("BT501");
            jSection.addItem("BT502");//3rd year 1st sem
            jSection.addItem("BT601");
            jSection.addItem("BT602");//2nd sem
            jSection.addItem("BT701");
            jSection.addItem("BT702");//4th year 1st sem
            jSection.addItem("BT801");
            jSection.addItem("BT802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BMMA")){
            jSection.removeAllItems();
            jSection.addItem("MMA101");
            jSection.addItem("MMA102");//1st year 1st sem
            jSection.addItem("MMA201");
            jSection.addItem("MMA202");//2nd sem
            jSection.addItem("MMA301");
            jSection.addItem("MMA302");//2nd year 1st sem
            jSection.addItem("MMA401");
            jSection.addItem("MMA402");//2nd sem
            jSection.addItem("MMA501");
            jSection.addItem("MMA502");//3rd year 1st sem
            jSection.addItem("MMA601");
            jSection.addItem("MMA602");//2nd sem
            jSection.addItem("MMA701");
            jSection.addItem("MMA702");//4th year 1st sem
            jSection.addItem("MMA801");
            jSection.addItem("MMA802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BSPsych")){
            jSection.removeAllItems();
            jSection.addItem("PSY101");
            jSection.addItem("PSY102");//1st year 1st sem
            jSection.addItem("PSY201");
            jSection.addItem("PSY202");//2nd sem
            jSection.addItem("PSY301");
            jSection.addItem("PSy302");//2nd year 1st sem
            jSection.addItem("PSY401");
            jSection.addItem("PSY402");//2nd sem
            jSection.addItem("PSY501");
            jSection.addItem("PSY502");//3rd year 1st sem
            jSection.addItem("PSY601");
            jSection.addItem("PSY602");//2nd sem
            jSection.addItem("PSY701");
            jSection.addItem("PSY702");//4th year 1st sem
            jSection.addItem("PSY801");
            jSection.addItem("PSY802");//2nd sem
        }
        else if (jCourse.getSelectedItem().equals("BSTM")){
            jSection.removeAllItems();
            jSection.addItem("TM101");
            jSection.addItem("TM102");//1st year 1st sem
            jSection.addItem("TM201");
            jSection.addItem("TM202");//2nd sem
            jSection.addItem("TM301");
            jSection.addItem("TM302");//2nd year 1st sem
            jSection.addItem("TM401");
            jSection.addItem("TM402");//2nd sem
            jSection.addItem("TM501");
            jSection.addItem("TM502");//3rd year 1st sem
            jSection.addItem("TM601");
            jSection.addItem("TM602");//2nd sem
            jSection.addItem("TM701");
            jSection.addItem("TM702");//4th year 1st sem
            jSection.addItem("TM801");
            jSection.addItem("TM802");//2nd sem
            
        }
        
    }//GEN-LAST:event_jCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> jSection;
    private javax.swing.JTextField jStudID;
    private javax.swing.JComboBox<String> jType;
    private javax.swing.JTextField jUsername;
    private javax.swing.JComboBox<String> jYear;
    private test.RoundedPanel roundedPanel1;
    private test.RoundedPanel roundedPanel2;
    private test.RoundedPanel roundedPanel3;
    private test.RoundedPanel roundedPanel4;
    private test.RoundedPanel roundedPanel5;
    private test.RoundedPanel roundedPanel6;
    // End of variables declaration//GEN-END:variables
}
