/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import java.awt.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.*;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class TeacherDashBoard extends javax.swing.JFrame {

    Pattern pattern;
    /**
     * Creates new form TeacherPage
     */
    public TeacherDashBoard(String user, String id) {
        
        initComponents();
        
        
        setTitle("Attendance Sheet");
        setVisible(true);
        setLocationRelativeTo(null);
        
        //addPlaceHolder(jTeachName);
        //addPlaceHolder(jTeachID);
        addPlaceHolder(jStudName);
        addPlaceHolder(jStudID);
        
        jTeachName.setText(user);
        jTeachID.setText(id);
        
        Connect();
        loadStudentInfo();
    }
    
    Connection con;
    private Statement pst;
    ResultSet rs;
    
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sql_student", "root", "ryujin04172001");
            pst = con.createStatement();
            System.out.println("Success");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TeacherDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void loadStudentInfo(){
//        try {
//            //pst = con.prepareStatement("SELECT subject FROM sql_student.all_subject");
//            rs = pst.executeQuery("SELECT * FROM sql_student.all_subject");
//            //jSubject.removeAll();
//            while(rs.next())
//                //jSubject.addItem(rs.getString(1));
//        } catch (SQLException ex) {
//            Logger.getLogger(TeacherDashBoard.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    
    //method for txt placeholder style and remove placeholder
    public void  addPlaceHolder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.GRAY);
    }
    
    public void removePlaceHolder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.BLACK);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTeachName = new javax.swing.JTextField();
        jTeachID = new javax.swing.JTextField();
        jStudName = new javax.swing.JTextField();
        jStudID = new javax.swing.JTextField();
        jShow = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSubject = new javax.swing.JComboBox<>();
        jDate = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 242, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(255, 242, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Sti.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 86, 225));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Attendance List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel4.setBackground(new java.awt.Color(255, 242, 0));

        jLabel3.setForeground(new java.awt.Color(40, 86, 225));
        jLabel3.setText("Student Name");

        jLabel4.setForeground(new java.awt.Color(40, 86, 225));
        jLabel4.setText("Student ID");

        jLabel5.setForeground(new java.awt.Color(40, 86, 225));
        jLabel5.setText("Status");

        jStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatusActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(40, 86, 225));
        jLabel6.setText("Teacher Name");

        jLabel7.setForeground(new java.awt.Color(40, 86, 225));
        jLabel7.setText("Teacher ID");

        jTeachName.setText("Teacher's Name");
        jTeachName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTeachNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTeachNameFocusLost(evt);
            }
        });

        jTeachID.setText("Teacher's ID");
        jTeachID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTeachIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTeachIDFocusLost(evt);
            }
        });

        jStudName.setText("Student Name");
        jStudName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jStudNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jStudNameFocusLost(evt);
            }
        });

        jStudID.setText("Student ID");
        jStudID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jStudIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jStudIDFocusLost(evt);
            }
        });

        jShow.setText("Update");
        jShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowActionPerformed(evt);
            }
        });

        jButton3.setText("Find");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSubject.setMaximumRowCount(20);
        jSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type", "Tertiary", "SHS" }));
        jSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTeachName, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(jTeachID)
                                .addComponent(jStudName, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jStudID, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTeachName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTeachID, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStudName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStudID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jShow)
                    .addComponent(jButton3))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 242, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Last", "Section", "Time"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatusActionPerformed
        // TODO add your handling code here:
        this.pattern = Pattern.compile("[0-9]{11}");
        
        if (jStudName != null && jStudID != null){
            String ID = jStudID.getText();
            Matcher match = pattern.matcher(ID);
            if (match.equals(jStudID)){
                jStatus.addItem("Present");
                jStatus.addItem("Absent");
                jStatus.addItem("Late");
            }
        }
    }//GEN-LAST:event_jStatusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String pid = jSubject.getSelectedItem().toString();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTeachNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTeachNameFocusGained
        // TODO add your handling code here:
        if (jTeachName.getText().equals("Teacher's Name")){
            jTeachName.setText(null);
            jTeachName.requestFocus();
            //remove placeholder style
            removePlaceHolder(jTeachName);
        }
    }//GEN-LAST:event_jTeachNameFocusGained

    private void jTeachIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTeachIDFocusGained
        // TODO add your handling code here:
        if (jTeachID.getText().equals("Teacher's ID")){
            jTeachID.setText(null);
            jTeachID.requestFocus();
            //remove placeholder style
            removePlaceHolder(jTeachID);
        }
    }//GEN-LAST:event_jTeachIDFocusGained

    private void jStudNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStudNameFocusGained
        // TODO add your handling code here:
        if (jStudName.getText().equals("Student Name")){
            jStudName.setText(null);
            jStudName.requestFocus();
            //remove placeholder style
            removePlaceHolder(jStudName);
        }
    }//GEN-LAST:event_jStudNameFocusGained

    private void jStudIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStudIDFocusGained
        // TODO add your handling code here:
        if (jStudID.getText().equals("Student ID")){
            jStudID.setText(null);
            jStudID.requestFocus();
            //remove placeholder style
            removePlaceHolder(jStudID);
        }
    }//GEN-LAST:event_jStudIDFocusGained

    private void jTeachNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTeachNameFocusLost
        // TODO add your handling code here:
        if (jTeachName.getText().length()==0){
            //add the place holder style
            addPlaceHolder(jTeachName);
            jTeachName.setText("Teacher's Name");
        }
    }//GEN-LAST:event_jTeachNameFocusLost

    private void jTeachIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTeachIDFocusLost
        // TODO add your handling code here:
        if (jTeachID.getText().length()==0){
            //add the place holder style
            addPlaceHolder(jTeachID);
            jTeachID.setText("Teacher's ID");
        }
    }//GEN-LAST:event_jTeachIDFocusLost

    private void jStudNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStudNameFocusLost
        // TODO add your handling code here:
        if (jStudName.getText().length()==0){
            //add the place holder style
            addPlaceHolder(jStudName);
            jStudName.setText("Student Name");
        }
    }//GEN-LAST:event_jStudNameFocusLost

    private void jStudIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jStudIDFocusLost
        // TODO add your handling code here:
        if (jStudID.getText().length()==0){
            //add the place holder style
            addPlaceHolder(jStudID);
            jStudID.setText("Student ID");
        }
    }//GEN-LAST:event_jStudIDFocusLost

    private void jSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubjectActionPerformed
        // TODO add your handling code here:
        
        BufferedReader reader = null;
        try {
            // TODO add your handling code here:
            String fileTertiary = "C:\\Users\\admin\\Documents\\NEWINFO\\Tertiary.txt";
            File file1 = new File(fileTertiary);
            reader = new BufferedReader(new FileReader(file1));
            
            int i = jTable1.getRowCount();
            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            
            
            
            
            if (jSubject.getSelectedItem().equals("Tertiary")){
                
                for(int j = 0; j < i; j++)
                    model1.removeRow(0);
                
                //get line from txt file
                Object[] tableLines = reader.lines().toArray();
                //extract data from txt
                for (Object tableLine : tableLines) {
                    String line = tableLine.toString().trim();
                    String[] dataRow = line.split("/");
                    //creates new row
                    model1.addRow(dataRow);
                }
            }
            String fileShs = "C:\\Users\\admin\\Documents\\NEWINFO\\SHS.txt";
            File file2 = new File(fileShs);
            reader = new BufferedReader(new FileReader(file2));
            
            int k = jTable1.getRowCount();
            DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
            //model2.setColumnIdentifiers(column2);
            
            
            
            if (jSubject.getSelectedItem().equals("SHS")){
                for(int j = 0; j < k; j++)
                    model2.removeRow(0);
                
                Object[] tableLines = reader.lines().toArray();
                //extract data from txt
                for (Object tableLine : tableLines) {
                    String line = tableLine.toString().trim();
                    String[] dataRow = line.split("/");
                    //creates new row
                    model1.addRow(dataRow);
                }
            }
            
            if (jSubject.getSelectedItem().equals("Type")){
                //remove the entire row
                for(int j = 0; j < i; j++)
                    model1.removeRow(0);
                //remove the entire row
                for(int j = 0; j < k; j++)
                    model2.removeRow(0);
            }
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TeacherDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TeacherDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(TeacherDashBoard.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        
        
        
//        if (jSubject.getSelectedItem().equals("Subject")){
//                jSection.removeAllItems();
//                jSection.addItem("Section");
//            }
//            else if (jSubject.getSelectedItem().equals("Computer Programming 2")){
//                jSection.removeAllItems();
//                jSection.addItem("Section");
//                jSection.addItem("BS201");
//                jSection.addItem("BS202");
//                jSection.addItem("BT201");
//                jSection.addItem("BT202");
//                jSection.addItem("BT203");
//            }
//            else if (jSubject.getSelectedItem().equals("NSTP 2")){
//                jSection.removeAllItems();
//                jSection.addItem("Section");
//                jSection.addItem("BS201");
//                jSection.addItem("BS202");
//                jSection.addItem("BT201");
//                jSection.addItem("BT202");
//                jSection.addItem("BT203");
//            }
//            else if (jSubject.getSelectedItem().equals("System Administration")){
//                jSection.removeAllItems();
//                jSection.addItem("Section");
//                jSection.addItem("BT201");
//                jSection.addItem("BT202");
//                jSection.addItem("BT203");
//            }
    }//GEN-LAST:event_jSubjectActionPerformed

    private void jShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowActionPerformed
        // TODO add your handling code here:
        String d = new SimpleDateFormat("MMMddyyyy").format(jDate.getDate()); 
        //Date format where MMM=month(Jun) dd=day and yyyy=year
        if (jSubject.getSelectedItem().equals("Tertiary")){
            Path filePath = Paths.get("C:\\Attendance\\Tertiary_records\\StudentLogins" + d + ".txt");
            //sets up the filepath and file name using Path object
            System.out.println(filePath);
        }
        if (jSubject.getSelectedItem().equals("SHS")){
            Path filePath = Paths.get("C:\\Attendance\\SHS_records\\StudentLogins" + d + ".txt");
            //sets up the filepath and file name using Path object
            System.out.println(filePath);
        }
    }//GEN-LAST:event_jShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TeacherDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jShow;
    private javax.swing.JComboBox<String> jStatus;
    private javax.swing.JTextField jStudID;
    private javax.swing.JTextField jStudName;
    private javax.swing.JComboBox<String> jSubject;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTeachID;
    private javax.swing.JTextField jTeachName;
    // End of variables declaration//GEN-END:variables
}
